CREATE TABLE IF NOT EXISTS user (
    `user_id` CHAR(128) NOT NULL,
    `usage` INT NOT NULL DEFAULT 0,
    `creation_time` DATETIME NOT NULL,
    `version` INT NOT NULL DEFAULT 0,
    PRIMARY KEY(`user_id`)
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS chat_id (
    `user_id` CHAR(128) NOT NULL COMMENT 'user id from wechat', 
    `chat_id` CHAR(128) NOT NULL COMMENT 'chat id generated by svr',
    PRIMARY KEY(`user_id`, `chat_id`)
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS chat_data (
    `idx` INT NOT NULL AUTO_INCREMENT,
    `chat_id` CHAR(128) NOT NULL,
    `role` CHAR(48) NOT NULL,
    `content` TEXT(32768) NOT NULL,
    `creation_time` DATETIME NOT NULL,
    PRIMARY KEY(`idx`, `chat_id`)
) ENGINE = InnoDB DEFAULT CHARSET=utf8;